name: format
on:
  pull_request:
permissions:
  pull-requests: read
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - run: echo noop
#      - uses: actions/checkout@v4.1.1
#      - uses: dart-lang/setup-dart@v1
#      - run: dart pub get
#      - run: dart format --set-exit-if-changed .
